#!/bin/bash

if test $# -ne 1
then
	echo "Usage: [program name] [number of repetitions]"
else
	rm -r Time	
	mkdir Time	
	for (( i = 1; i <= $1; i++ ))
	do
		for j in ./Files/*
		do
			file=$(echo $j | awk -F/ '{print $3}')
			echo >> ./Time/$file.txt
			echo >> ./Time/$file.txt
			echo >> ./UserTime/$file.txt
			echo >> ./UserTime/$file.txt
			echo "Test $i">> ./Time/$file.txt
			echo "Test $i">> ./UserTime/$file.txt
			{ time maude.linux $j/kk | grep "rewrites" >> ./Time/$file.txt; } 2>> ./UserTime/$file.txt
			echo "Calculated the test $i of the file $file"
		done
	done
fi
